# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170419_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='favorite',
        ),
    ]
